### ISSUE TITLE
Game gets stuck loading a world indefinitely

### ISSUE THREAD

**Issue by UnstableStrafe** [ChaoticTrials/SimpleBackups#15]
### Minecraft version

1.19.4

### Simple Backups version

1.19.4-2.2.1

### Forge version

43.2.0

### The latest.log file

https://pastebin.com/GHMvSuAY

### Issue description

Minecraft will not load a world, instead staying on the loading screen indefinitely.

### Steps to reproduce

1. Open a world
2. Wait

### Other information

The main reason I think this mod is causing it is because it seemed to be the only mod in the crash log too. 
[crash-2023-04-05_14.26.13-server.txt](https://github.com/MelanX/SimpleBackups/files/11162026/crash-2023-04-05_14.26.13-server.txt)

**Comment by MelanX** [comment]
Your MC version is 1.19.2, not 1.19.4.
Anyways, I think it was a problem that I released this file for older MC versions. I’ll just remove the tags for the old versions. If this still happens in 1.19.4, please comment here and I’ll reopen it.

**Comment by UnstableStrafe** [comment]
There was no option to select 1.19.2, so I just chose the only 1.19 option I had

**Comment by MelanX** [comment]
Oh true, I changed the template, sorry!
