### ISSUE TITLE
Incorrect version identification

### ISSUE THREAD

**Issue by ColonelGerdauf** [ChaoticTrials/SimpleBackups#17]
### Minecraft version

1.19.4

### Simple Backups version

1.19.4-2.2.0

### Forge version

43.2.14

### The latest.log file

https://pastebin.com/mT1EwCt6

### Issue description

The version for 1.19.4 is listed as installable for instances under 1.19.2 and 1.19.3, on both Curseforge and Modrinth. This is a problem when you update a 1.19.2 version via launchers. 1.19 is unusual with its subversions. 1.19-1.19.2, 1.19.3, and 1.19.4 are distinct from one another, and mixing mods across them will create compatibility problems.

**Comment by MelanX** [comment]
I forgot to remove it on the newest version, thanks for pointing out!

**Comment by VOLKOUL** [comment]
Is this why I can't generate/load a world on 1.19.2? **OH BRUH..**. It just freezes on the default dirt screen. I had to manually check 300 mods (**pain**) to determine which one causes the issue. _⁽ᵇᵘᵗ ᴵ ʷᵃˢ ᵛᶦᶜᵗᵒʳᶦᵒᵘˢ  *ᶦⁿˢᵉʳᵗ ˢᵐᵘᵍ ᶠᵃᶜᵉ⁾_

Could you maybe fix the incorrect version identification so that the curseforge launcher doesn't show an "available update" all the time? Thank you :D

**Comment by MelanX** [comment]
I already changed it, all 1.19.4 versions shouldn’t have the other versions anymore. Same for modrinth. If it’s still tagged wrongly, I’ll check it later when back on computer.

**Comment by VOLKOUL** [comment]
Thank ya!

**Comment by ColonelGerdauf** [comment]
Once again, the newest version was tagged incorrectly to include a 1.19.4 version in a 1.19.2 instance.

You should either put something to automate the specificity task, or do something to prevent such a thing from happening again.

**Comment by MelanX** [comment]
Sorry, forgot to change it. Here it's changed and will never happen again: https://github.com/MelanX/SimpleBackups/commit/41bf8744fa8d33e8b45b5be22d3245d7f16c2b9f

**Comment by VOLKOUL** [comment]
In the curseforge launcher the 1.19.4-2.2.2 file **still** shows up in the update section for 1.19.2 mods.
Since 2.2.3 is out you could probably remove the 2.2.2 so it doesn't appear anymore.

**Comment by MelanX** [comment]
I already did that. I don’t know what’s wrong at CurseForge. I already contacted them about this problem on the discord server. Will open a ticket.
