### ISSUE TITLE
On CurseForge 1.19.4-2.2.2 version is incorrectly marked as compatible with 1.19.2

### ISSUE THREAD

**Issue by JoshHawley** [ChaoticTrials/SimpleBackups#18]
### Minecraft version

1.19.4

### Simple Backups version

1.19.4-2.2.2

### Forge version

43.2.14

### The latest.log file

N/A

### Issue description

On CurseForge, the version 1.19.4-2.2.2 is incorrectly marked as compatible for 1.19.2, and that causes the Curseforge client to mark it as a mod that needs updating. If you are on 1.19.2 this causes a crash (ABSENT) because it requires 1.19.4.

### Steps to reproduce

1. Create new forge modpack on CurseForge for minecraft 1.19.2
2. Install SimpleBackups-1.19.1-2.1.9.jar (this specific version) using curseforge
3. Load the modpack to verify it works
4. Close minecraft
5. Inside CurseForge client push refresh button on mods list
6. Update SimpleBackups (this will install SimpleBackups-1.19.4-2.2.2.jar)
7. Load the modpack and it will crash

**Comment by MelanX** [comment]
It isn’t tagged for 1.19.2, that’s why I already opened a ticket on CurseForge. I know it’s annoying, but at the moment I can’t do anything. It’s completely CurseForges fault. Yes, I tagged them for 1.19.2 before but this was removed around one week ago.

**Comment by JoshHawley** [comment]
Makes sense. Curseforge is both a blessing and a curse at times it seems.

**Comment by MelanX** [comment]
Should be fixed :)
> Hey MelanX!
> 
> Thank you very much for contacting us, I will do my best to assist you with CurseForge :)
> ​
> We invalidated the mentioned file, please let me know if this resolved the issue.
> 
> Not an NPC,
> 
> https://support.overwolf.com/helpdesk/tickets/170141
> CurseForge Support Team
