### ISSUE TITLE
[1.20.1] Command to do manual backup

### ISSUE THREAD

**Issue by SigmaFlame** [ChaoticTrials/SimpleBackups#23]
### Describe your idea

Hello, I would like to suggest you a command to do manual backup.
For Forge 1.20.1 of course. Thanks in advance.

**Comment by MelanX** [comment]
`/simplebackups backup start`

**Comment by SigmaFlame** [comment]
I tryed, but the command /simplebackups does not exists.
Maybe this command does not exist on Forge?

**Comment by MelanX** [comment]
It does. Do you have permission to execute it? Cheats enabled/op level 2 or higher.
