### ISSUE TITLE
Add command for manually start a backup

### ISSUE THREAD

**Issue by joaoa-casagrande** [ChaoticTrials/SimpleBackups#28]
### Describe your idea

I've been using this mod for quite a while and I notices that it doesn't have a command to force a backup. Usually what I do is wait for the backup to start and finish before I leave, but it's kinda annoying.

Is it possible to add a command like `/simplebackups start`?

**Comment by MelanX** [comment]
`/simplebackups backup start` exists. You need permission level 2 (cheats enabled), or enable it for everyone in the server config, located in the world.
