### ISSUE TITLE
Server hanging when simpleBackups tries to delete old backups.

### ISSUE THREAD

**Issue by StormCircuit** [ChaoticTrials/SimpleBackups#4]
### Minecraft version

1.18.2

### Simple Backups version

1.1.5

### Forge version

40.0.41

### The latest.log file

https://pastebin.com/RWS9HRK5

### Issue description

Simplebackups starts a backup and then consumes the tick cycle until the server crashes. It is worth noting I use symbolic junction links to backup files. In this scenario the simplebackups file is the original file and the junction link is on another drive.

### Steps to reproduce

Get a backup scheduled
Join a server to start it as configured above
Witness a crash due to server watchdog. 

### Other information

Modpack is latest version here:
https://www.curseforge.com/minecraft/modpacks/attlerock-1-18
crash log: https://pastebin.com/5S981Pmc

**Comment by MelanX** [comment]
What is you exact config for that? When trying to reproduce, I get an exception because this file already exists. 
Maybe my English wasn't good enough to understand but I think I did it correctly.

**Comment by StormCircuit** [comment]
I used a junction symbolic link. So To be specific I used:
"mklink /J 'target on the other drive' 'simplebackups folder' "

**Comment by StormCircuit** [comment]
And not a problem at all, let me know if I can provide anymore info! Love the mod!

**Comment by MelanX** [comment]
To be honest, I never did something like that and trying to reproduce that results in the same error as before: An exception that the file already exists... Why are you using this link and not setting this path directly?

Thank you!

**Comment by MelanX** [comment]
I know, you should never just download a zip file or jar. This is a jar in a zip file :D Could you please test this? I don't want to just publish it without being sure that it fixes your problem because it *could* introduce more bugs.
[SimpleBackups-1.18.2-Test-1.1.0.zip](https://github.com/MelanX/SimpleBackups/files/8460002/SimpleBackups-1.18.2-Test-1.1.0.zip)

**Comment by StormCircuit** [comment]
I will try it! I honestly somehow didn't know about the other directory. The last backup mod didn't support it so I assumed yours wouldnt as well. My bad. I will try the config change too.

**Comment by StormCircuit** [comment]
Appears to work, dropped it in as a replacement and it completed a backup without issue of 18 GB. Thank you!

**Comment by MelanX** [comment]
Awesome, will upload the fix later, then you can get an official version :)
