### ISSUE TITLE
add the ability to merge partial backups with the last full backup and restore

### ISSUE THREAD

**Issue by MisteryDuck** [ChaoticTrials/SimpleBackups#40]
### Describe your idea

I see there is an ability to merge and restore, but not on the 1,19 version of the mod? Could this be backported please? Our server's world got corrupted today and I had to manually merge two days worth of backups

**Comment by MelanX** [comment]
If you need to do this anytime soon, you could just use the 1.20 version to merge the zips. Will backport this feature, just can’t give an ETA.

**Comment by MelanX** [comment]
Oh, I just saw that the 1.19 version of the mod already has this feature. As you can see on this link, the 1.19.x branch has the command: https://github.com/ChaoticTrials/SimpleBackups/blob/1.19.x/src/main/java/de/melanx/simplebackups/commands/MergeCommand.java
And here is the version where it was introduced: https://modrinth.com/mod/simple-backups/version/1.19.4-2.2.6

**Comment by MisteryDuck** [comment]
oh, I see. It's not on curseforge, the last version there is 2.1.10. My bad then

**Comment by MelanX** [comment]
Here is the CurseForge link to the same mod version: https://www.curseforge.com/minecraft/mc-mods/simple-backups/files/5123564

**Comment by MisteryDuck** [comment]
oh. no. It's the the subversion tags, the latest versions are tagged only for 1.19.4. Does the 1.19.4 version work for 1.19.2?

**Comment by MelanX** [comment]
I think it doesn't work. Normally, I'd tag the older versions if I know that it works. In this case, I specifically removed theses tags here: https://github.com/ChaoticTrials/SimpleBackups/commit/41bf8744fa8d33e8b45b5be22d3245d7f16c2b9f
There must be a reason for that. But you can try!

**Comment by MisteryDuck** [comment]
all right, I'll check if it works

**Comment by MisteryDuck** [comment]
nope, it doesn't work. The mod doesn't get rejected by the game, but it throws a error on world generation

**Comment by MelanX** [comment]
I backported it to 1.19.2 :) Version 1.19.1-2.1.11

**Comment by MisteryDuck** [comment]
no way, that was fast! Thank you very much!
