### ISSUE TITLE
Server crash when server tries to delete a backup.

### ISSUE THREAD

**Issue by StormCircuit** [ChaoticTrials/SimpleBackups#5]
### Minecraft version

1.18.2

### Simple Backups version

1.1.6

### Forge version

40.0.41

### The latest.log file

https://pastebin.com/9TSWpX2D

### Issue description

Server appears to be failing to delete a file. Latest version of simplebackups.

### Steps to reproduce

Setup the symbolic junction link, same as the last bug report. Setup a world. Attempt a backup. I am not sure why the world sometimes fails and other times succeeds but once it begins to fail it doesn't stop.

### Other information

Crash report: https://pastebin.com/HfmLv0JG

**Comment by MelanX** [comment]
These are sad news. And again, it happens while deleting... hm... no idea right now, will look at it sometimes. For now, you can try the direct/normal path. If it happens with this option, too... that would be very bad :D

**Comment by StormCircuit** [comment]
It does actually happen with the normal option. I tried setting it to a normal path on the same drive "E:\servers\webservers" and it crashes on startup. I will try to dig up the crash log when I can.

**Comment by MelanX** [comment]
Please try again with the new version. If it still happens, feel free to re-open this issue.
