### ISSUE TITLE
Messages not appearing when a backup is made

### ISSUE THREAD

**Issue by Nevrai** [ChaoticTrials/SimpleBackups#7]
### Minecraft version

1.18.2

### Simple Backups version

1.1.1.0

### Forge version

40.1.79

### The latest.log file

https://pastebin.com/raw/K9KGNKbt

### Issue description

Messages are not showing up anywhere when a backup is made, despite the “Send Messages” config option being enabled. I’ve set backups to occur every 20 minutes, and eight backups have been made so far, but I’ve not seen any messages, either in chat or above my hotbar. Don’t remember where they’re supposed to appear, but I’ve not seen any. I don’t see a message anywhere when creating a backup manually using the `/simplebackups backup start` command either. Backups _are_ made, both manual and automatic ones, but messages do not show up.

**Comment by MelanX** [comment]
Do you have op permission? If not, that’s why. The message is only being sent to players with permission level 2 or higher.

**Comment by Nevrai** [comment]
@MelanX I’m in single-player. Could, perhaps, a config option be added to remove the permission requirement? I’d very much like to see the messages without having to have cheats enabled, as well as being able to start manual backups. I feel like that’d be a nice change, especially since this was the case in prior versions of the mod.
